server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: trace

  tomcat:
    max-swallow-size: 100MB

spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  application:
    name: pet-me
  datasource:
    url: jdbc:postgresql://localhost:5432/pet-me
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    validate-on-migrate: true
    placeholder-replacement: false

  security:
    user:
      name: ${SECURITY_NAME:tanita}
      password: ${SECURITY_PASSWORD:dev}

#  config:
#    import: application_prod.yaml
#  profiles:
#    active: prod

storage:
  s3:
    credentials:
      access-key: ""
      secret-key: ""
    bucket: pet-me
    stuck:
      auto: false
    region:
      static: us-east-1
    host: https://localhost.localstack.cloud:4566

s3:
  client:
    connection-timeout: 2000
    max-error-retry: 0
    socket-timeout: 5000

